import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter-sans",
})

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html className={`${inter.variable} antialiased`} lang="en">
			<body>{children}</body>
		</html>
	)
}
